### ISSUE TITLE
Challenges with seting up files in directory

### ISSUE THREAD

**Issue by EFLS** [akirak/org-starter#5]
Hi akirak,

Thanks for this promising package.

I'm trying to add a directory and set up hotkeys for some files in it.

    (org-starter-define-directory "~/Dropbox/org/"
      :agenda t
      :files
        ("notes.org"
         :key "n"))

Yet when I try to execute the above code, I get a message:

    org-starter-define-directory: Invalid function: "notes.org"

What am I missing?

Thanks
EFLS

**Comment by EFLS** [comment]
Ah, now that I look at it again, I guess there are brackets missing...

So it needs to be

    :files
      (("notes.org" :key "n"))

Makes sense... 😄

**Comment by akirak** [comment]
You need to quote (i.e. prepend `'`) the file list:

```emacs-lisp
(org-starter-define-directory "~/Dropbox/org/"
  :agenda t
  :files
    '(("notes.org" :key "n"))
 ```

This is because `org-starter-define-file` and `org-starter-define-directory` are functions. The arguments inside the definition are evaluated before they are passed to the function. This might be confusing since the package claims to be "use-package for Org mode", but it is common in Emacs Lisp.

`org-starter-def` is a macro, so you don't have to quote its arguments.

**Comment by akirak** [comment]
> Thanks for this promising package.

Thank you for the compliment. It is my current "flagship" repository, so I am willing to develop it further.

**Comment by akirak** [comment]
My example was wrong, so I've fixed it. Sorry for the mistake.

I'm not using `org-starter-define-directory` for myself. I set `org-starter-path` in my `custom-file` and use `org-starter-def` and `org-starter-define-file` to define files. I personally prefer this way of setup.

**Comment by EFLS** [comment]
Thanks for the explanation.

I switched to using the macro `org-starter-def` and it works swimmingly!

One thing I currently don't understand that well, is what `org-starter-path` does -- I couldn't figure it out from the documentation. Does it work as a "base directory" of sorts?

EDIT: Would it be useful to share a basic setup somewhere? Maybe in the readme, or in a wiki? I'm willing to share my setup once I finetune it.

**Comment by akirak** [comment]
> One thing I currently don't understand that well, is what org-starter-path does -- I couldn't figure it out from the documentation. Does it work as a "base directory" of sorts?

`org-starter-path` does the following things (at present):

- `org-starter-define-file` (and `org-starter-def`) looks for a file from the directories in the variable. You don't have to specify a directory for each Org file.
- You can put your configuration in `.org-config.el` in the path. Then you can search configuration in the files using `org-starter-swiper-config-files`.

It is useful especially if you have multiple repositories for Org files. This way I manage different Org repositories for different scopes/contexts (e.g. work and personal). `org-starter-path` can be saved in `custom-file`, and I use different custom files for different machines, so I use `.org-config.el` files for context-specific configuration, while keeping my common configuration in a public GitHub repository. I want to share this setup with people.

You can also add directories to the variable through `org-starter-define-directory` with `:add-to-path` set to t.

> EDIT: Would it be useful to share a basic setup somewhere? Maybe in the readme, or in a wiki? 

Yes, welcome! If you have a public GitHub repository for your Emacs-related stuffs, I will add it to the README of this package. Writing blog posts would be another way to contribute to the package, and I'm actually interested in how people use my package. I'm looking forward to seeing it.
